/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.proyectoChatCliente.gui;

import java.awt.Frame;
import javax.swing.ImageIcon;

/**
 *
 * @author martin
 */
public class CuadroMsg extends javax.swing.JDialog {

    private final ImageIcon icono;
    
    /**
     * Creates new form CuadroMsg
     * @param parent
     * @param modal
     * @param img
     * @param texto
     */
    public CuadroMsg(java.awt.Frame parent, boolean modal, ImageIcon img, String texto) {
        super(parent, modal);
        setLocationRelativeTo(null);
        icono = null;
        initComponents();
        lblIcono.setIcon(img);
        msgCuadro.setText(texto);
        
        if (!isVisible()) setVisible(Boolean.TRUE);
        
        
    }

    public CuadroMsg(Frame parent, boolean modal) {
        super(parent, modal);
        setLocationRelativeTo(parent);
        icono = new ImageIcon(getClass().getResource("/org/proyectoChatCliente/resources/loader.gif"));
        initComponents();
        lblIcono.setIcon(icono);
        icono.setImageObserver(lblIcono);
    }

    public void showOpenDialog(){
        setVisible(true);
    }
    
    public void hide(){
        setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcono = new javax.swing.JLabel();
        msgCuadro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        lblIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/proyectoChatCliente/resources/loader.gif"))); // NOI18N

        msgCuadro.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 24)); // NOI18N
        msgCuadro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msgCuadro.setText("Iniciando Sesion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(msgCuadro, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblIcono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgCuadro)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel msgCuadro;
    // End of variables declaration//GEN-END:variables
}
