/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.proyectoChatCliente.gui;

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.proyectoChatCliente.net.Conector;
import org.proyectoChatComun.base.Mensaje;
import org.proyectoChatComun.base.PaqueteInicial;

/**
 *
 * @author martin
 */
public class PanelChat extends javax.swing.JPanel {

    public int usuarioReceptor;
    private PaqueteInicial paqIni;
    private Conector cliente;
    
    public PanelChat(int usuarioReceptor) {
        this.usuarioReceptor = usuarioReceptor;
        initComponents();
        txtChat.setEditable(false);
        setSize(615, 261);
    }
    
    public PanelChat(int usuarioReceptor, PaqueteInicial paqIni, Conector cliente){
        this.usuarioReceptor = usuarioReceptor;
        this.paqIni = paqIni;
        this.cliente = cliente;
        initComponents();
        setSize(615, 261);
    }

    private void send(Mensaje msg) throws IOException{
        
        cliente.sendObject(msg);
        addMsg(msg);
    }
    
    public void addMsg(Mensaje msg){
        
        if (msg.getTexto().endsWith("\n")) txtChat.setText(txtChat.getText() + msg);
        
        else txtChat.setText(txtChat.getText() + msg + "\n");

        txtMsg.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        txtChat = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtMsg = new javax.swing.JTextArea();

        jScrollPane6.setViewportView(txtChat);

        txtMsg.setColumns(20);
        txtMsg.setRows(5);
        txtMsg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMsgKeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(txtMsg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            .addComponent(jScrollPane6)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMsgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMsgKeyPressed

        String msgEscrito = txtMsg.getText().trim();
        boolean mensajeVacio = msgEscrito.isEmpty();
        
        if (evt.isShiftDown() && evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtChat.setText(msgEscrito + txtMsg.getText().trim() + "\n");
        }
        else if (!evt.isShiftDown() && evt.getKeyCode() == KeyEvent.VK_ENTER) {

            try {
                if (!mensajeVacio) {
                    
                    Mensaje msg = new Mensaje(msgEscrito, paqIni.getUser().getId(), usuarioReceptor);
                    System.out.println(msg.getTexto());
                    send(msg);
                }

            } catch (IOException ex) {
                Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtMsgKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextPane txtChat;
    private javax.swing.JTextArea txtMsg;
    // End of variables declaration//GEN-END:variables
}
