/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.proyectoServer.gui;

import org.proyectoChatComun.base.Usuario;
import org.proyectoServer.db.Database;
import org.proyectoServer.db.Status;

/**
 *
 * @author martin
 */
public class CuadroOptions extends javax.swing.JDialog {

    private Usuario selected;

    public CuadroOptions(java.awt.Frame parent, boolean modal, Usuario selected, boolean isHabilitado) {
        super(parent, modal);
        this.selected = selected;
        lblNickUser.setText(selected.toString());
        btnDisableUser.setEnabled(isHabilitado);
        btnEnableUser.setEnabled(!isHabilitado);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnableUser = new javax.swing.JButton();
        btnDisableUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNickUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnEnableUser.setText("Habilitar");
        btnEnableUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableUserActionPerformed(evt);
            }
        });

        btnDisableUser.setText("Deshabilitar");
        btnDisableUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisableUserActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/proyectoServer/resources/user.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblNickUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNickUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNickUser.setText("[Nick User]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEnableUser)
                        .addGap(28, 28, 28)
                        .addComponent(btnDisableUser))
                    .addComponent(lblNickUser, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblNickUser)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEnableUser)
                            .addComponent(btnDisableUser)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnableUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableUserActionPerformed

        Database.setStatusUser(selected.getNick(), Status.HABILITADO);
    }//GEN-LAST:event_btnEnableUserActionPerformed

    private void btnDisableUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisableUserActionPerformed

        Database.setStatusUser(selected.getNick(), Status.DESHABILITADO);
        
    }//GEN-LAST:event_btnDisableUserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisableUser;
    private javax.swing.JButton btnEnableUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNickUser;
    // End of variables declaration//GEN-END:variables
}
